ServiceHost/Areas/Admin/Pages/Accounts/Index.cshtml.cs
using System.Collections.Generic;
using _0_Framework.Application;
using _0_Framework.Infrastructure;
using AccountManagement.Application.Contracts.Account;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Admin.Pages.Accounts
{
    //[Authorize(Roles = Roles.User)]

    public class IndexModel : PageModel
    {
        public AccountSearchModel SearchModel;
        public List<AccountViewModel> Accounts;
        public SelectList Roles;
        private readonly IAccountApplication _accountApplication;
        private readonly IRoleApplication _roleApplication;
        private readonly IFileUploader _fileUploader;


        public IndexModel(IAccountApplication accountApplication, IFileUploader fileUploader, IRoleApplication roleApplication)
        {
            _accountApplication = accountApplication;
            _roleApplication = roleApplication;
            _fileUploader = fileUploader;
        }

        public void OnGet(AccountSearchModel searchModel)
        {
            Accounts = _accountApplication.Search(searchModel);
            Roles = new SelectList(_roleApplication.GetRoles(),"Id","Title");
        }
        public IActionResult OnGetCreate()
        {
            var command = new RegisterAccount
            {
                Roles = _roleApplication.GetRoles()
            };
            return Partial("Create", command);
        }
        public JsonResult OnPostCreate(RegisterAccount command)
        {
            var result = _accountApplication.Register(command);
            return new JsonResult(result);
        }
        public IActionResult OnGetEdit(long id)
        {
            var account = _accountApplication.GetDetail(id);
            account.Roles = _roleApplication.GetRoles();

            return Partial("Edit", account);
        }
        public JsonResult OnPostEdit(EditAccount command)
        {
            var result = _accountApplication.Edit(command);
            return new JsonResult(result);
        }
        public IActionResult OnGetChangePassword(long id)
        {
            var account = _accountApplication.GetDetailPassword(id);

            return Partial("ChangePassword", account);
        }
        public JsonResult OnPostChangePassword(ChangePassword command)
         {
            var result = _accountApplication.ChangePassword(command);
            return new JsonResult(result);
        }
    }
}

ServiceHost/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class AboutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ServiceHost/Pages/AccessDenied.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ServiceHost/Pages/Account.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountManagement.Application.Contracts.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class AccountModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        private readonly IAccountApplication _accountApplication;
        public AccountModel(IAccountApplication accountApplication)
        {
            _accountApplication = accountApplication;
        }

        public void OnGet()
        {
        }
        public IActionResult OnPostLogin(Login command)
        {
            var result = _accountApplication.Login(command);
            if (result.IsSuccedded)
                return RedirectToPage("/Index", new { area = "Admin" }); 
            Message = result.Message;
            return RedirectToPage("/Account");

        }
        public IActionResult OnGetLogout()
        {
            _accountApplication.Logout();
            return RedirectToPage("./Account");
        }
    }
}

ServiceHost/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class ContactModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ServiceHost/Pages/ContactInfo.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class ContactInfoModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ServiceHost/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ServiceHost.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ServiceHost/Pages/Index.cshtml.cs
using System.Collections.Generic;
using _01_HaidariehQuery.Contracts.Ceremonies;
using _01_HaidariehQuery.Contracts.Multimedias;
using Haidarieh.Application.Contracts.Member;
using Haidarieh.Application.Contracts.Multimedia;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class IndexModel : PageModel
    {
        public CreateMember Member { get; set; }
        public string ErrorMessage { get; set; }
        public string SuccessMessage { get; set; }
        public List<MultimediaQueryModel> ceremony { get; set; }
        public CeremonyQueryModel searchModel { get; set; }

        private readonly IMemberApplication _memberApplication;
        private readonly IMultimediaApplication _multimediaApplication;
        private readonly ICeremonyQuery _ceremonyQuery;
        



        public IndexModel(IMemberApplication memberApplication, IMultimediaApplication multimediaApplication, ICeremonyQuery ceremonyQuery)
        {
            _memberApplication = memberApplication;
            _multimediaApplication = multimediaApplication;
            _ceremonyQuery = ceremonyQuery;
        }

        public void OnGet()
        {

        }
        public void OnPostCreate(CreateMember Member)
        {

            if (!ModelState.IsValid)
            {
                ErrorMessage = "اطلاعات ثبت نگردید. لطفاً مجدداً تلاش نمائید.";
            }
            else
            {
                _memberApplication.Create(Member);
                SuccessMessage = "اطلاعات با موفقیت ثبت گردید. با تشکر.";
                ModelState.Clear();
            }
        }
        public JsonResult OnGetAddVisitCount(long id)
        {
            var newnumber = _multimediaApplication.AddVisitCount(id);
            return new JsonResult(newnumber);
        }
        public RedirectToPageResult OnGetSearch(string search)
        {
            return RedirectToPage("/Search?search=", search);
        }
    }
}

ServiceHost/Pages/Membership.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Haidarieh.Application.Contracts.Member;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class MembershipModel : PageModel
    {
        public string ErrorMessage { get; set; }
        public string SuccessMessage { get; set; }

        private readonly IMemberApplication _imemberApplication;

        public MembershipModel(IMemberApplication imemberApplication)
        {
            _imemberApplication = imemberApplication;
        }

        public void OnGet()
        {

        }
        public void OnPost(CreateMember command)
        {
            if (!ModelState.IsValid)
            {
                ErrorMessage = "اطلاعات ثبت نگردید. لطفاً مجدداً تلاش نمائید.";
            }
            else
            {
                _imemberApplication.Create(command);
                SuccessMessage = "اطلاعات با موفقیت ثبت گردید. با تشکر.";
                ModelState.Clear();
            }
        }
    }
}

ServiceHost/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ServiceHost.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ServiceHost/Pages/Register.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountManagement.Application.Contracts.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class RegisterModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        private readonly IAccountApplication _accountApplication;

        public RegisterModel(IAccountApplication accountApplication)
        {
            _accountApplication = accountApplication;
        }

        public void OnGet()
        {
        }
        public IActionResult OnPostRegister(RegisterAccount command)
        {
            var result = _accountApplication.Register(command);
            if(result.IsSuccedded)
                return RedirectToPage("./Account");
            Message = result.Message;
            return RedirectToPage("./Register");

        }
    }
}

ServiceHost/Pages/Search.cshtml.cs
using _01_HaidariehQuery.Contracts.Ceremonies;
using _01_HaidariehQuery.Contracts.Multimedias;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Linq;

namespace ServiceHost.Pages
{
    public class SearchModel : PageModel
    {
        private readonly ICeremonyQuery _ceremonyQuery;
        public List<MultimediaQueryModel> ceremony { get; set; }
        public CeremonyQueryModel searchModel { get; set; }



        public SearchModel(ICeremonyQuery ceremonyQuery)
        {
            _ceremonyQuery = ceremonyQuery;
        }
        public void OnGet(string search)
        {
            var searchmodel = new CeremonyQueryModel();
            if (!string.IsNullOrWhiteSpace(search))
            {
                searchmodel.Title = search;
                ceremony = _ceremonyQuery.Search(search);
            }
            else
            {
                ceremony = null;
            }
        }
        public void OnPostSearch(CeremonyQueryModel searchmodel, int pageId = 1)
        {
            if (!string.IsNullOrWhiteSpace(searchmodel.Title))
            {
                ceremony = _ceremonyQuery.Search(searchmodel.Title);
            }
            else
            {
                ceremony= null;
            }
        }

    }

}

ServiceHost/Pages/Support.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class SupportModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ServiceHost/ViewComponents/BannersViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using _01_HaidariehQuery.Contracts.Ceremonies;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.FileProviders;
using System.Linq;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.ViewFeatures;

namespace ServiceHost.ViewComponents
{
    public class BannersViewComponent: ViewComponent
    {
        private readonly ICeremonyQuery _ceremonyQuery;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public List<string> ImageList { get; set; }


        public BannersViewComponent(ICeremonyQuery ceremonyQuery, IWebHostEnvironment webHostEnvironment)
        {
            _ceremonyQuery = ceremonyQuery;
            _webHostEnvironment = webHostEnvironment;
        }

        public IViewComponentResult Invoke()
        {
            var provider = new PhysicalFileProvider(_webHostEnvironment.WebRootPath);
            var contents = provider.GetDirectoryContents(Path.Combine("Theme", "Images"));
            var objFiles = contents.OrderBy(m => m.LastModified);
            ImageList = new List<string>();
            foreach (var item in objFiles.ToList())
            {
                ImageList.Add(item.Name);
            }
            ViewData["ImageList"] = ImageList;
            var banner = _ceremonyQuery.GetComingBanner();
            return View(banner);
        }

    }
}

ServiceHost/ViewComponents/MembershipViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ServiceHost.ViewComponents
{
    public class MembershipViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

ServiceHost/ViewComponents/PastAudiosViewComponent.cs
using _01_HaidariehQuery.Contracts.Multimedias;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ServiceHost.ViewComponents
{
    public class PastAudiosViewComponent:ViewComponent
    {
        private readonly IMultimediaQuery _multimediaQuery;

        public PastAudiosViewComponent(IMultimediaQuery multimediaQuery)
        {
            _multimediaQuery = multimediaQuery;
        }
        public IViewComponentResult Invoke()
        {
            var pastAudios = _multimediaQuery.GetMultimediasWithCeremony(2).Take(4);
            return View(pastAudios);
        }
    }
}

ServiceHost/ViewComponents/SponsorsViewComponent.cs
using _01_HaidariehQuery.Contracts.Sponsers;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ServiceHost.ViewComponents
{
    public class SponsorsViewComponent:ViewComponent
    {
        private readonly ISponsorQuery _sponsorQuery;

        public SponsorsViewComponent(ISponsorQuery sponsorQuery)
        {
            _sponsorQuery = sponsorQuery;
        }

        public IViewComponentResult Invoke()
        {
            var sopnsers = _sponsorQuery.GetAll();
            return View(sopnsers);
        }
    }
}

ServiceHost/Pages/About.cshtml
@page
@model AboutModel
@{ Layout = "_Layout2";
    ViewData["title"] = "درباره ما"; }
<section id="About">
    <div class="gap">
        <div class="container">
            <div class="hstry-wrap">
                <div class="row">
                    <div class="col-md-6 col-sm-12 col-lg-6">
                        <div class="hstry-img text-center">
                            <img src="~/Theme/assets/images/resources/hstry-img.png" alt="hstry-img.png">
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12 col-lg-6">
                        <div class="hstry-desc">
                            <span>چند کلمه ای درباره ما</span>
                            <h2>تاریخچه حیدریة النجف الاشرف</h2>
                            <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد.</p>
                            <strong>حیدریة النجف الاشرف <span>اولین</span> حیدریة النجف الاشرف در <span>کشور</span> است.</strong>
                            <ul>
                                <li>تحقیقات اسلامی</li>
                                <li>کمک به اقشار حیدریة النجف الاشرف</li>
                                <li>هدایت رویداد های کمک</li>
                                <li>تحصیل کودکان</li>
                                <li>کمک به گرسنگان و نیازمندان</li>
                                <li>اقامه نماز و مراسم اسلامی</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div><!-- History Wrap -->
        </div>
    </div>
</section>

ServiceHost/Pages/AccessDenied.cshtml
@page
@model ServiceHost.Pages.AccessDeniedModel
@{
}

<h1>دوست عزیز! شما دسترسی به این صفحه ندارید.</h1>

ServiceHost/Pages/Account.cshtml
@page
@model ServiceHost.Pages.AccountModel
@{ Layout = "_Layout"; }

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
    <meta name="author" content="Coderthemes">

    <link rel="shortcut icon" href="images/favicon_1.ico">

    <title>ورود به صفحه مدیریت سایت</title>

    <!-- Base Css Files -->
    <link href="css/bootstrap.min.css" rel="stylesheet" />

    <!-- Font Icons -->
    <link href="~/admintheme/assets/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/admintheme/assets/ionicon/css/ionicons.min.css" rel="stylesheet" />
    <link href="~/admintheme/assets/css/material-design-iconic-font.min.css" rel="stylesheet">

    <!-- animate css -->
    <link href="~/admintheme/assets/css/animate.css" rel="stylesheet" />

    <!-- Waves-effect -->
    <link href="~/admintheme/assets/css/waves-effect.css" rel="stylesheet">

    <!-- Custom Files -->
    <link href="~/admintheme/assets/css/helper.css" rel="stylesheet" type="text/css" />
    <link href="~/admintheme/assets/css/style.css" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <script src="~/admintheme/assets/js/modernizr.min.js"></script>

</head>
<body>


    <div class="wrapper-page">
        <div class="panel panel-color panel-primary panel-pages">
            <div class="panel-heading bg-img">
                <div class="bg-overlay"></div>
                <h3 class="text-center m-t-10 text-white"> ورود به <strong>پنل مدیریت سایت</strong> </h3>
            </div>


            <div class="panel-body">
                <form method="post" class="form-horizontal m-t-20" asp-page-handler="login">

                    <div class="form-group ">
                        <div class="col-xs-12">
                            <input class="form-control input-lg " name="Username" id="username" type="text" required="" autocomplete="on" placeholder="نام کاربری">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-xs-12">
                            <input class="form-control input-lg" name="Password" type="password" id="password" required="" autocomplete="on" placeholder="کلمه عبور">
                        </div>
                    </div>

                    <div class="form-group ">
                        <div class="col-xs-12">
                            <div class="checkbox checkbox-primary">
                                <input id="checkbox-signup" type="checkbox">
                                <label for="checkbox-signup">مرا بخاطر بسپار</label>
                            </div>

                        </div>
                    </div>

                    <div class="form-group text-center m-t-40">
                        <div class="col-xs-12">
                                <button class="btn btn-primary btn-lg w-lg waves-effect waves-light" type="submit">ورود</button>
                        </div>
                    </div>

                    @*<div class="form-group m-t-30">
                        <div class="col-sm-7">
                            <a href="recoverpw.html"><i class="fa fa-lock m-r-5"></i> فراموشی رمز عبور</a>
                        </div>
                        <div class="col-sm-5 text-right">
                            <a asp-page="register">ثبت نام</a>
                        </div>
                    </div>*@
                </form>
                @if (Model.Message != null)
                {
            <div class="alert alert-danger">@Model.Message</div>}
            </div>

        </div>
    </div>


    <script>
        var resizefunc = [];
    </script>
    <script src="~/admintheme/assets/js/jquery.min.js"></script>
    <script src="~/admintheme/assets/js/bootstrap.min.js"></script>
    <script src="~/admintheme/assets/js/waves.js"></script>
    <script src="~/admintheme/assets/js/wow.min.js"></script>
    <script src="~/admintheme/assets/js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="~/admintheme/assets/js/jquery.scrollTo.min.js"></script>
    <script src="~/admintheme/assets/jquery-detectmobile/detect.js"></script>
    <script src="~/admintheme/assets/fastclick/fastclick.js"></script>
    <script src="~/admintheme/assets/jquery-slimscroll/jquery.slimscroll.js"></script>
    <script src="~/admintheme/assets/jquery-blockui/jquery.blockUI.js"></script>


    <!-- CUSTOM JS -->
    <script src="~/admintheme/assets/js/jquery.app.js"></script>

</body>
</html>




@*<div class="container">*@

@*<div class="gap clearfix">
    <div class="d-flex justify-content-center h-100">
        <div class="card">
            <div class="card-header">
                <h3 class="rtl abot-sec">ورود</h3>
            </div>
            <div class="card-body">
                <form method="post" asp-page-handler="Login">
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text input-icon"><i class="fa fa-user"></i></span>
                        </div>
                        <input type="text" name="Username" class="form-control" id="username" value="" autocomplete="on" placeholder="نام کاربری">
                    </div>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text input-icon"><i class="fa fa-key"></i></span>
                        </div>
                        <input type="password" name="Password" class="form-control" id="password" value="" autocomplete="on" placeholder="کلمه عبور">
                    </div>
                    <div class="form-group">
                        <input type="submit" class="abot-wrap badge-success alert" value="ورود">
                    </div>
                </form>
                @if (Model.Message != null)
                {
                    <div class="alert alert-danger">@Model.Message</div>
                }
            </div>
            <div class="card-footer">
                <div class="d-flex justify-content-center links">
                    هنوز ثبت نام نکرده اید؟<a asp-page="Register" class="text-success">ثبت نام</a>
                </div>
                <div class="d-flex justify-content-center">
                    <a href="#">بازگردانی رمز عبور!</a>
                </div>
            </div>
        </div>
    </div>
    </div>*@

@*<script src="~/theme/assets/js/jquery-3.1.1.min.js"></script>*@

@*</div>*@

ServiceHost/Pages/Index.cshtml
@page

@model ServiceHost.Pages.IndexModel
@{ ViewData["Title"] = "حیدریه النجف الاشرف"; }


@await Component.InvokeAsync("Banners")

@*<partial name="About" />*@

<div id="ReloadMostVisitedCeremonies">
    @await Component.InvokeAsync("MostVisitedCeremonies")
</div>

@*<partial name="Services" />*@

@await Component.InvokeAsync("PastEvents")

<div id="ReloadPastAudios">
    @await Component.InvokeAsync("PastAudios")
</div>


@await Component.InvokeAsync("Sponsors")

@*@await Component.InvokeAsync("Membership")*@


<section class="section section-contact" id="contact2">
    <div class="gap thm-layer opc9">
        <div class="fixed-bg" style="background-image: url(~/wwwroot/Theme/assets/images/parallax7.jpg);"></div>
        <div class="container">
            <div class="nwsltr-wrp text-center">
                <div class="nwsltr-innr">
                    <div class="nwsltr-title">
                        <h3>عضویت بانک اعضای حیدریه</h3>
                        <span>دریافت آخرین اخبار و مجالس حیدریه</span>
                    </div>
                    <form method="post">
                        @if (!string.IsNullOrWhiteSpace(Model.SuccessMessage))
                        {
            <div class="alert-success p-1 rounded-pill">
                <i class="alert-success"></i>
                <p>@Model.SuccessMessage</p>
            </div>}
                        @if (!string.IsNullOrWhiteSpace(Model.ErrorMessage))
                        {
            <div class="alert-danger p-1rounded-pill">
                <i class="alert-danger"></i>
                <p>@Model.ErrorMessage</p>
            </div>}
                        <div class="row">
                            <div class="col-lg-6">
                                <input asp-for="Member.FullName" type="text" class="form-control b-box" placeholder="*نام و نام خانوادگی ">
                                <span asp-validation-for="Member.FullName" class="text-danger"></span><span></span>
                            </div>
                            <div class="col-lg-6">
                                <input asp-for="Member.Mobile" type="tel" class="form-control b-box" placeholder="*تلفن همراه">
                                <span asp-validation-for="Member.Mobile" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12" style="padding-top:20px">
                                <button type="submit" asp-page-handler="Create" class="btn md-vertical-align-center">عضویت در خبرنامه</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

</section>


@*<div class="text-center">
        <h1 class="display-4">Welcome</h1>
        <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    </div>*@

ServiceHost/Pages/Membership.cshtml
@page
@model ServiceHost.Pages.MembershipModel
@{
}

ServiceHost/Pages/Register.cshtml
@page
@model ServiceHost.Pages.RegisterModel
@{
    ViewData["Title"] = "ثبت نام";
}

<div class="gap clearfix">
    <div class="container">
        <div class="d-flex justify-content-center h-100">
            <div class="card">
                <div class="card-header">
                    <h3 class="rtl abot-sec">ثبت نام</h3>
                </div>
                <div class="card-body">
                    @if(Model.Message!=null)
                    {
                        <div class="danger alert-danger">@Model.Message</div>
                    }
                    <form method="post" asp-page-handler="Register">
                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text input-icon"><i class="fa fa-address-card-o"></i></span>
                            </div>
                            <input type="text" size="50" class="form-control" name="fname" id="txt-fname" placeholder="نام ">
                        </div>
                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text input-icon"><i class="fa fa-address-card-o"></i></span>
                            </div>
                            <input type="text" size="50" class="form-control" name="lname" id="txt-lname" placeholder="نام خانوادگی">
                        </div>
                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text input-icon"><i class="fa fa-mobile-phone"></i></span>
                            </div>
                            <input type="tel" size="50" class="form-control" name="mobile" id="txt-mobile" placeholder="موبایل">
                        </div>
                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text input-icon"><i class="fa fa-user"></i></span>
                            </div>
                            <input type="text" size="50" class="form-control" name="username" id="txt-username" placeholder="نام کاربری">
                        </div>
                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text input-icon"><i class="fa fa-key"></i></span>
                            </div>
                            <input type="password" size="50" class="form-control" name="password" id="txt-password" placeholder="رمز عبور">
                        </div>
                        @*<div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text input-icon"><i class="fa fa-user"></i></span>
                            </div>
                            <input type="text" size="50" class="form-control" name="repassword" id="txt-repassword" placeholder="تکرار رمز عبور">
                        </div>*@
                        <div class="form-group">
                            <input type="submit" value="ثبت نام" class="abot-wrap badge-success alert">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>