ServiceHost/Areas/Admin/Pages/CeremonyGuests/Create.cshtml.cs
using _0_Framework.Application.Email;
using _0_Framework.Infrastructure;
using Haidarieh.Application.Contracts.Ceremony;
using Haidarieh.Application.Contracts.CeremonyGuest;
using Haidarieh.Application.Contracts.Guest;
using Haidarieh.Configuration.Permissions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;

namespace ServiceHost.Areas.Admin.Pages.CeremonyGuests
{
    public class CreateModel : PageModel
    {
        private readonly ICeremonyGuestApplication _ceremonyGuestApplication;
        private readonly ICeremonyApplication _ceremonyApplication;
        private readonly IGuestApplication _guestApplication;
        //public CreateCeremonyGuest CeremonyGuest;
        private readonly IEmailService _emailService;
        public GuestSearchModel SearchModel;
        public List<GuestViewModel> Guests;
        public EditCeremonyGuest ceremonyGuest;


        public CreateModel(IGuestApplication guestApplication, ICeremonyApplication ceremonyApplication, ICeremonyGuestApplication ceremonyGuestApplication, IEmailService emailService)
        {
            _guestApplication = guestApplication;
            _ceremonyApplication = ceremonyApplication;
            _ceremonyGuestApplication = ceremonyGuestApplication;
            _emailService = emailService;
        }

        public void OnGet(GuestSearchModel searchModel, long ceremonyId)
        {

            ceremonyGuest = _ceremonyGuestApplication.GetDetail(ceremonyId);
            ceremonyGuest.Guests = _ceremonyGuestApplication.GetRestGuests(ceremonyGuest.Guests);
            //Guests = _guestApplication.Search(searchModel);

            //CeremonyGuest = new CreateCeremonyGuest
            //{
            //    Ceremonies = _ceremonyApplication.GetUpcommingCeremonies(),
            //    Guests = _guestApplication.GetGuests()
            //};
        }

        //[NeedPermission(HPermissions.EditCeremonyGuest)]
        public IActionResult OnPostCreate(EditCeremonyGuest command,int[] chk)
        {

            _ceremonyGuestApplication.Edit(command, chk);
            //return new ation(result);
            return RedirectToPage("./Index");


            //var result = _ceremonyGuestApplication.Create(command);
            //var ceremony = _ceremonyApplication.GetDetail(command.CeremonyId);
            //var guests = _ceremonyGuestApplication.GetCeremonyGuests(command.CeremonyId);
            //var guestInfo = _guestApplication.GetGuestsInfo(guests);
            //foreach (var item in guestInfo)
            //{
            //    _emailService.SendEmail(ceremony.Title, " جناب آقای دعوتنامه شرکت در در مراسم", item.Email);
            //}

            //return new JsonResult(result);
        }
        //public IActionResult OnGetEdit(long ceremonyId)
        //{
        //    //var selectedceremony = _ceremonyApplication.GetDetail(ceremonyId);
        //    //selectedceremony.CeremonyGuests = _ceremonyGuestApplication.GetCeremonyGuests(ceremonyId);
        //    ceremonyGuest = _ceremonyGuestApplication.GetDetail(ceremonyId);
        //    ceremonyGuest.Guests = _ceremonyGuestApplication.GetGuests();
        //    //ceremonyGuest.Guests = _ceremonyGuestApplication.GetCeremonyGuests(ceremonyId);
        //    //ViewData["guests"] = _guestApplication.GetGuests();
        //    //ceremonyGuest.Guests = _guestApplication.GetGuests();
        //    //ceremonyGuest.Ceremonies = _ceremonyApplication.GetCeremonies();
        //    return Partial("Edit", ceremonyGuest);
        //}

        //public JsonResult OnGetEdit(EditCeremonyGuest command, int[] chk)
        //{

        //    var result = _ceremonyGuestApplication.Edit(command, chk);
        //    return new JsonResult(result);
        //}
    }
}

ServiceHost/Areas/Admin/Pages/Multimedias/EditAlbum.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Infrastructure;
using Haidarieh.Application.Contracts.CeremonyGuest;
using Haidarieh.Application.Contracts.Multimedia;
using Haidarieh.Configuration.Permissions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Admin.Pages.Multimedias
{
    public class EditAlbumModel : PageModel
    {
        public List<MultimediaViewModel> Command { get; set; }
        public object ViewBag { get; private set; }
        public SelectList Guests;

        //public MultimediaViewModel MVM { get; set; }
        private readonly ICeremonyGuestApplication _ceremonyGuestApplication;
        private readonly IMultimediaApplication _multimediaApplication;

        public EditAlbumModel(ICeremonyGuestApplication ceremonyGuestApplication, IMultimediaApplication multimediaApplication)
        {
            _ceremonyGuestApplication = ceremonyGuestApplication;
            _multimediaApplication = multimediaApplication;
        }
        public void OnGet(long Id)
        {
            ViewBag = Id;
            Command = _multimediaApplication.GetMultimediasWithCeremony(Id);
        }
        public IActionResult OnPost(EditMultimedia command, List<IFormFile> files)
        {
            var result = _multimediaApplication.EditAlbum(command, files);
            return RedirectToPage("./EditAlbum");
        }
        [NeedPermission(HPermissions.EditMultimedia)]
        public IActionResult OnGetRemove(long id,long ceremonyId)
        {
            _multimediaApplication.Delete(id);
            //var showList=OnGetShow(command);
            //return Partial("Show", showList);
            //return new JsonResult(result);
            return RedirectToPage("./EditAlbum", new { id = ceremonyId });
        }
        public IActionResult OnGetAdd(long id)
        {
            var command = _multimediaApplication.GetDetail(id);
            command.Guests = _ceremonyGuestApplication.GetCeremonyGuestsVM(id); //new SelectList(_ceremonyGuestApplication.GetCeremonyGuestsVM(id), "Id", "Title");
            return Partial("./Add", command);


        }
        public JsonResult OnPostAdd(EditMultimedia createcommand, List<IFormFile> FileAddress)
        {
            var result = _multimediaApplication.EditAlbum(createcommand, FileAddress);
            return new JsonResult(result);
        }
    }
}

ServiceHost/Areas/Admin/Pages/Multimedias/Index.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using _0_Framework.Infrastructure;
using _01_HaidariehQuery.Contracts.Ceremonies;
using _01_HaidariehQuery.Query;
using Haidarieh.Application.Contracts.Ceremony;
using Haidarieh.Application.Contracts.CeremonyGuest;
using Haidarieh.Application.Contracts.Multimedia;
using Haidarieh.Configuration.Permissions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Admin.Pages.Multimedias
{ 
    public class IndexModel : PageModel
    {
        public MultimediaSearchModel SearchModel;
        //public IEnumerable<IGrouping<long, MultimediaViewModel>> Multimedias;
        public List<MultimediaViewModel> Multimedias { get; set; }
        public SelectList Ceremonies;
        public SelectList Guests;
        private readonly IMultimediaApplication _multimediaApplication;
        private readonly ICeremonyApplication _ceremonyApplication;
        private readonly ICeremonyGuestApplication _ceremonyGuestApplication;


        public IndexModel(IMultimediaApplication multimediaApplication, ICeremonyApplication ceremonyApplication, ICeremonyGuestApplication ceremonyGuestApplication)
        {
            _multimediaApplication = multimediaApplication;
            _ceremonyApplication = ceremonyApplication;
            _ceremonyGuestApplication = ceremonyGuestApplication;
        }

        [NeedPermission(HPermissions.ListMultimedia)]
        public void OnGet(MultimediaSearchModel searchModel)
        {
            Multimedias=_multimediaApplication.Search(searchModel);
            Ceremonies = new SelectList(_ceremonyApplication.GetCeremonies(),"Id","Title");

        }
        public IActionResult OnGetCreate()
        {
            var command = new CreateMultimedia
            {
                Ceremonies = _ceremonyApplication.GetCeremonies()
            };
            return Partial("./Create", command);
        }

        [NeedPermission(HPermissions.CreateMultimedia)]
        public JsonResult OnPostCreate(CreateMultimedia createcommand,List<IFormFile> FileAddress)
        {
            var result = _multimediaApplication.Create(createcommand, FileAddress);
            return new JsonResult(result);
        }
        public IActionResult OnGetEditMetadata(long id)
        {
            var multimedia = _multimediaApplication.GetDetail(id);
            multimedia.Ceremonies = _ceremonyApplication.GetCeremonies();
            return Partial("./EditMetadata", multimedia);
        }

        //public IActionResult OnGetEditAlbum(long id)
        //{
        //    var multimedia = _multimediaApplication.GetDetail(id);
        //    multimedia.Ceremonies = _ceremonyApplication.GetCeremonies();
        //    return Partial("./EditAlbum", multimedia);
        //}

        [NeedPermission(HPermissions.EditMultimedia)]
        public JsonResult OnPostEditMetadata(EditMultimedia command)
        {
            var result = _multimediaApplication.EditMetadata(command);
            return new JsonResult(result);
        }

        //[NeedPermission(HPermissions.EditMultimedia)]
        //public JsonResult OnPostEditAlbum(EditMultimedia command, List<IFormFile> FileAddress)
        //{
        //    var result = _multimediaApplication.EditAlbum(command, FileAddress);
        //    return new JsonResult(result);
        //}
        public IActionResult OnGetShow(long ceremonyid)
        {
            var multimedias = _multimediaApplication.GetMultimediasWithCeremony(ceremonyid);
            return Partial("Show", multimedias);
        }
        public JsonResult OnGetFillCeremonyGuests(long Id)
        {
            var guestList = _ceremonyGuestApplication.GetGuests(Id);
            return new JsonResult(guestList);
        }
    }
}

ServiceHost/Areas/Admin/Pages/Roles/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Admin.Pages.Roles
{
    public class CreateModel : PageModel
    {
        private readonly IRoleApplication _roleApplication;
        public CreateRole command;
        public CreateModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public void OnGet()
        {
        }
        public IActionResult OnPost(CreateRole command)
        {
            var result = _roleApplication.Create(command);
            return RedirectToPage("Index"); 
        }
    }
}

ServiceHost/Areas/Admin/Pages/Multimedias/Add.cshtml
@model Haidarieh.Application.Contracts.Multimedia.EditMultimedia
@{ }

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">اضافه نمودن فایل</h4>
</div>

<form asp-page="./EditAlbum" asp-page-handler="Add"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Title" class="control-label">مجلس</label>
                    <input type="text" readonly class="form-control" asp-for="Title">
                    <span asp-validation-for="Title" class="error"></span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="GuestId" class="control-label">میهمان</label>
                    <select type="text" class="form-control" id="gstList" asp-for="GuestId" asp-items='new SelectList(Model.Guests,"Id","FullName")'>  @*onchange="FillSerializeDropdown('CeremonyId','FillCeremonyGuests','GuestId')">*@
                    @*<select class="form-control" asp-for="GuestId">*@
                        <option value="0">انتخاب میهمان</option>
                    </select>
                    <span asp-validation-for="GuestId" class="error"></span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="FileAddress" class="control-label">فایل</label>
                    <input type="file" multiple="multiple" class="form-control" asp-for="FileAddress" id="Files">
                    <span asp-validation-for="FileAddress" class="error"></span>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                @*<progress class="progress-bar progress-bar-warning progress-bar-striped active" id="fileProgress" style="display: none"></progress>*@
                
                                <div class="progress" id="progress" style="display: none">
                                    <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuemin="0" aria-valuemax="100"></div>
                                </div> 
                 
            </div>
        </div>
        <input type="hidden" asp-for="CeremonyId" value="@Model.CeremonyId">
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
        @*<input type="button"  id="btnUpload" value="Upload" />*@
        @*<td colspan="2">*@
        @*</td>*@
    </div>
</form>

ServiceHost/Areas/Admin/Pages/Multimedias/Create.cshtml
@model Haidarieh.Application.Contracts.Multimedia.CreateMultimedia
@{ }

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ایجاد فایل جدید</h4>
</div>

<form asp-page="./Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="CeremonyId" class="control-label">مراسم</label>
                    <select type="text" class="form-control" id="cerList" asp-for="CeremonyId" asp-items='new SelectList(Model.Ceremonies,"Id","Title")' onchange="FillSerializeDropdown('CeremonyId','FillCeremonyGuests','GuestId')">
                        <option value="0">انتخاب مراسم</option>
                    </select>
                    <span asp-validation-for="CeremonyId" class="error"></span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="GuestId" class="control-label">میهمان</label>
                    @*<select type="text" class="form-control" id="gstList" asp-for="GuestId" asp-items='new SelectList(Model.Guests,"Id","Title")'>*@
                    <select class="form-control" asp-for="GuestId">
                        <option value="0">انتخاب میهمان</option>
                    </select>
                    <span asp-validation-for="GuestId" class="error"></span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="FileAddress" class="control-label">فایل</label>
                    <input type="file" multiple="multiple" class="form-control" asp-for="FileAddress">
                    <span asp-validation-for="FileAddress" class="error"></span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <div class="progress" id="progress" style="display: none">
                        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="FileTitle" class="control-label">عنوان فایل</label>
                    <input type="text" class="form-control" asp-for="FileTitle" onchange="fillField('FileTitle', 'FileAlt')" />
                    <span asp-validation-for="FileTitle" class="error"></span>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="FileAlt" class="control-label">عنوان فایل در گوگل</label>
                    <input type="text" class="form-control" asp-for="FileAlt">
                    <span asp-validation-for="FileAlt" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

@section Scripts
{
    <script src="~/AdminTheme/assets/js/site.js"></script>

    <script>
        $("#ddlIncidents").change(function () {
            var value = $(this).children(":selected").attr("id");
            console.log(value);
            $("#selectedItem").text(value);
        });

    </script>
}

ServiceHost/Areas/Admin/Pages/Multimedias/EditAlbum.cshtml
@page
@model ServiceHost.Areas.Admin.Pages.Multimedias.EditAlbumModel
@{
    Layout = "Shared/_AdminLayout";
    ViewData["title"] = "ویرایش فایلهای چندرسانه ای";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
        <p class="pull-left">
            <a class="btn btn-success btn-lg" href="#showmodal=@Url.Page("./EditAlbum", "Add", new { id = Model.ViewBag })">اضافه نمودن فایل چندرسانه ای </a>
        </p>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> ویرایش فایلهای آلبوم </h3>
            </div>
            <div class="panel-body">
                <form method="get" enctype="multipart/form-data">
                    <div class="row">
                        <div class="col-md-12">
                            <table id="datatable" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>عکس</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{ int m = Model.Command.Count % 4;}
                                    @{ int k = Model.Command.Count - 1;}
                                    @{ int t = 0;}

                                    @if (m == 0)
                                    {
                                        @for (int i = 0; i < Model.Command.Count / 4; i++)
                                        {
                                            <tr>
                                                @for (int j = 0; j < 4; j++)
                                                {
                                                <td>

                                                    @if (Model.Command[t].ContentType.StartsWith("audio/"))
                                                    {

                                                        <a data-fancybox="gallery" data-caption="@Model.Command[t].Title" href="~/@Model.Command[t].FileAddress" data-type="video" style="width: 70px; height: 70px;">
                                                            <img src="~/Theme/assets/images/video__player__movie.jpg" style="width: 70px; height: 70px;" />
                                                        </a>
                                                        <span>@Model.Command[t].Guest</span>

                                                    }
                                                    else if (Model.Command[t].ContentType.StartsWith("video/"))
                                                    {
                                                        <a data-fancybox="gallery" data-caption="@Model.Command[t].Title" href="~/@Model.Command[t].FileAddress">
                                                            <img src="~/Theme/assets/images/film.png" style="width: 70px; height: 70px" />
                                                        </a>
                                                        <span>@Model.Command[t].Guest</span>

                                                    }
                                                    else if (Model.Command[t].ContentType.StartsWith("image/"))
                                                    {
                                                        <a data-fancybox="gallery" data-caption="@Model.Command[t].Title" href="~/@Model.Command[t].FileAddress">
                                                            <img src="~/@Model.Command[t].FileAddress" style="width: 70px; height: 70px" />
                                                        </a>
                                                    }

                                                </td>
                                                    <td>
                                                        <a class="btn btn-warning pull-right m-rl-5" asp-page="./EditAlbum" asp-page-handler="Remove" asp-route-id="@Model.Command[t].Id" asp-route-ceremonyId="@Model.Command[j].CeremonyId">
                                                            <i class="fa fa-edit"></i>حذف
                                                        </a>
                                                        <input type="hidden" asp-for="@Model.Command[t].CeremonyId" value="@Model.Command[t].CeremonyId">
                                                    </td>
                                                    t += 1;
                                                }
                                            </tr>
                                        }
                                    }
                                    else
                                    {
                                        @for (int i = 0; i < Model.Command.Count / 4 + 1; i++)
                                        {
                                            t = 0;
                                            <tr>
                                                @while (t < 4 && k >= 0)
                                                {
                                                <td>
                                                    @if (Model.Command[k].ContentType.StartsWith("audio/"))
                                                    {

                                                        <a data-fancybox="gallery" data-caption="@Model.Command[k].Title" href="~/@Model.Command[k].FileAddress" data-type="video" style="width: 70px; height: 70px;">
                                                            <img src="~/Theme/assets/images/video__player__movie.jpg" style="width: 70px; height: 70px;" />
                                                        </a>
                                                        <span>@Model.Command[k].Guest</span>

                                                    }
                                                    else if (Model.Command[k].ContentType.StartsWith("video/"))
                                                    {
                                                        <a data-fancybox="gallery" data-caption="@Model.Command[k].Title" href="~/@Model.Command[k].FileAddress">
                                                            <img src="~/Theme/assets/images/film.png" style="width: 70px; height: 70px" />
                                                        </a>
                                                        <span>@Model.Command[k].Guest</span>

                                                    }
                                                    else if (Model.Command[k].ContentType.StartsWith("image/"))
                                                    {
                                                        <a data-fancybox="gallery" data-caption="@Model.Command[k].Title" href="~/@Model.Command[k].FileAddress">
                                                            <img src="~/@Model.Command[k].FileAddress" style="width: 70px; height: 70px" />
                                                        </a>
                                                    }
                                                </td>
                                                    <td>
                                                        <a class="btn btn-warning pull-right m-rl-5" asp-page="EditAlbum" asp-page-handler="Remove" asp-route-id="@Model.Command[k].Id" asp-route-ceremonyId="@Model.Command[k].CeremonyId">
                                                            <i class="fa fa-edit"></i>حذف
                                                        </a>
                                                        <input type="hidden" asp-for="@Model.Command[k].CeremonyId" value="@Model.Command[k].CeremonyId">
                                                    </td>
                                                    t += 1;
                                                    k -= 1;
                                                }
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                    @*<input type="hidden" asp-for="MVM.CeremonyId" value="@Model.MVM.CeremonyId">*@

                </form>
            </div>
        </div>
    </div>
</div>

ServiceHost/Areas/Admin/Pages/Multimedias/EditMetadata.cshtml
@model Haidarieh.Application.Contracts.Multimedia.EditMultimedia
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش فایل</h4>
</div>

<form asp-page="./Index" asp-page-handler="EditMetadata"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="CeremonyId" class="control-label">مراسم</label>
                    <select type="text" class="form-control" asp-for="CeremonyId" asp-items='new SelectList(Model.Ceremonies,"Id","Title")' onchange="fillField('selectedItem', 'Title')">
                        <option value="0">انتخاب مراسم</option>
                    </select>
                    <span asp-validation-for="CeremonyId" class="error"></span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Title" class="control-label">عنوان</label>
                    <input type="text" class="form-control" asp-for="Title">
                    <span asp-validation-for="Title" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="FileTitle" class="control-label">عنوان فایل</label>
                    <input type="text" class="form-control" asp-for="FileTitle" onchange="fillField('FileTitle', 'FileAlt')" />
                    <span asp-validation-for="FileTitle" class="error"></span>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="FileAlt" class="control-label">عنوان فایل در گوگل</label>
                    <input type="text" class="form-control" asp-for="FileAlt">
                    <span asp-validation-for="FileAlt" class="error"></span>
                </div>
            </div>
        </div>
            <input type="hidden" asp-for="Id" value="@Model.Id">

        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
            <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
        </div>
</form>