ServiceHost/Areas/Admin/Pages/Ceremonies/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Infrastructure;
using _01_HaidariehQuery.Contracts.Ceremonies;
using Haidarieh.Application.Contracts.Calendar;
using Haidarieh.Application.Contracts.Ceremony;
using Haidarieh.Configuration.Permissions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Admin.Pages.Ceremonies
{
    public class IndexModel : PageModel
    {
        private readonly ICeremonyApplication _ceremonyApplication;
        private readonly ICalendarApplication _calendarApplication;

        public List<CeremonyViewModel> Ceremonies;
        public CeremonySearchModel SearchModel;

        public IndexModel(ICeremonyApplication ceremonyApplication, ICalendarApplication calendarApplication)
        {
            _ceremonyApplication = ceremonyApplication;
            _calendarApplication = calendarApplication;
        }

        [NeedPermission(HPermissions.ListCeremony)]
        public void OnGet(CeremonySearchModel searchModel)
        {
            Ceremonies=_ceremonyApplication.Search(searchModel);
        }

        [NeedPermission(HPermissions.ListCalendar)]
        public IActionResult OnGetCreate()
        {
            var command = new CreateCeremony()
            {
                Calendars = _calendarApplication.GetCalendars()
            };
            return Partial("Create", command);
        }

        [NeedPermission(HPermissions.CreateCeremony)]
        public JsonResult OnPostCreate(CreateCeremony command)
        {
            var result = _ceremonyApplication.Create(command);
            return new JsonResult(result);
        }
        public IActionResult OnGetEdit(long id)
        {
            var ceremony = _ceremonyApplication.GetDetail(id);
            return Partial("Edit", ceremony);
        }
    
        [NeedPermission(HPermissions.EditCeremony)]
        public JsonResult OnPostEdit(EditCeremony command)
        {
            var result = _ceremonyApplication.Edit(command);
            return new JsonResult(result);
        }

        [NeedPermission(HPermissions.LogCeremony)]
        public IActionResult OnGetLog()
        {
            var logs = _ceremonyApplication.GetCeremonyWithOperationsLog();
            return Partial("OperationLog", logs);
        }

    }
}

ServiceHost/Areas/Admin/Pages/CeremonyGuests/Create.cshtml.cs
using _0_Framework.Application.Email;
using _0_Framework.Infrastructure;
using Haidarieh.Application.Contracts.Ceremony;
using Haidarieh.Application.Contracts.CeremonyGuest;
using Haidarieh.Application.Contracts.Guest;
using Haidarieh.Configuration.Permissions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;

namespace ServiceHost.Areas.Admin.Pages.CeremonyGuests
{
    public class CreateModel : PageModel
    {
        private readonly ICeremonyGuestApplication _ceremonyGuestApplication;
        private readonly ICeremonyApplication _ceremonyApplication;
        private readonly IGuestApplication _guestApplication;
        //public CreateCeremonyGuest CeremonyGuest;
        private readonly IEmailService _emailService;
        public GuestSearchModel SearchModel;
        public List<GuestViewModel> Guests;
        public EditCeremonyGuest ceremonyGuest;


        public CreateModel(IGuestApplication guestApplication, ICeremonyApplication ceremonyApplication, ICeremonyGuestApplication ceremonyGuestApplication, IEmailService emailService)
        {
            _guestApplication = guestApplication;
            _ceremonyApplication = ceremonyApplication;
            _ceremonyGuestApplication = ceremonyGuestApplication;
            _emailService = emailService;
        }

        public void OnGet(GuestSearchModel searchModel, long ceremonyId)
        {

            ceremonyGuest = _ceremonyGuestApplication.GetDetail(ceremonyId);
            ceremonyGuest.Guests = _ceremonyGuestApplication.GetRestGuests(ceremonyGuest.Guests);
            //Guests = _guestApplication.Search(searchModel);

            //CeremonyGuest = new CreateCeremonyGuest
            //{
            //    Ceremonies = _ceremonyApplication.GetUpcommingCeremonies(),
            //    Guests = _guestApplication.GetGuests()
            //};
        }

        //[NeedPermission(HPermissions.EditCeremonyGuest)]
        public IActionResult OnPostCreate(EditCeremonyGuest command,int[] chk)
        {

            _ceremonyGuestApplication.Edit(command, chk);
            //return new ation(result);
            return RedirectToPage("./Index");


            //var result = _ceremonyGuestApplication.Create(command);
            //var ceremony = _ceremonyApplication.GetDetail(command.CeremonyId);
            //var guests = _ceremonyGuestApplication.GetCeremonyGuests(command.CeremonyId);
            //var guestInfo = _guestApplication.GetGuestsInfo(guests);
            //foreach (var item in guestInfo)
            //{
            //    _emailService.SendEmail(ceremony.Title, " جناب آقای دعوتنامه شرکت در در مراسم", item.Email);
            //}

            //return new JsonResult(result);
        }
        //public IActionResult OnGetEdit(long ceremonyId)
        //{
        //    //var selectedceremony = _ceremonyApplication.GetDetail(ceremonyId);
        //    //selectedceremony.CeremonyGuests = _ceremonyGuestApplication.GetCeremonyGuests(ceremonyId);
        //    ceremonyGuest = _ceremonyGuestApplication.GetDetail(ceremonyId);
        //    ceremonyGuest.Guests = _ceremonyGuestApplication.GetGuests();
        //    //ceremonyGuest.Guests = _ceremonyGuestApplication.GetCeremonyGuests(ceremonyId);
        //    //ViewData["guests"] = _guestApplication.GetGuests();
        //    //ceremonyGuest.Guests = _guestApplication.GetGuests();
        //    //ceremonyGuest.Ceremonies = _ceremonyApplication.GetCeremonies();
        //    return Partial("Edit", ceremonyGuest);
        //}

        //public JsonResult OnGetEdit(EditCeremonyGuest command, int[] chk)
        //{

        //    var result = _ceremonyGuestApplication.Edit(command, chk);
        //    return new JsonResult(result);
        //}
    }
}

ServiceHost/Areas/Admin/Pages/Roles/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Admin.Pages.Roles
{
    public class CreateModel : PageModel
    {
        private readonly IRoleApplication _roleApplication;
        public CreateRole command;
        public CreateModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public void OnGet()
        {
        }
        public IActionResult OnPost(CreateRole command)
        {
            var result = _roleApplication.Create(command);
            return RedirectToPage("Index"); 
        }
    }
}

ServiceHost/Areas/Admin/Pages/Roles/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Infrastructure;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Admin.Pages.Roles
{
    public class EditModel : PageModel
    {
        private readonly IRoleApplication _roleApplication;
        public EditRole command;
        public List<SelectListItem> Permissions=new List<SelectListItem>();
        private readonly IEnumerable<IPermissionExposer> _exposers;
        public EditModel(IRoleApplication roleApplication, IEnumerable<IPermissionExposer> exposers)
        {
            _roleApplication = roleApplication;
            _exposers = exposers;
        }
        public void OnGet(long id)
        {
            command = _roleApplication.GetDetail(id);
            var permissions = new List<PermissionDto>();
            foreach (var exposer in _exposers)
            {
                var exposedPermission = exposer.Expose();
                foreach (var (key,value) in exposedPermission)
                {
                    permissions.AddRange(value);
                    var group = new SelectListGroup()
                    {
                        Name = key
                    };
                    foreach (var permission in value)
                    {
                        var item = new SelectListItem(permission.Name, permission.Code.ToString())
                        {
                            Group=  group
                        };
                        if (command.MappedPermissions.Any(x => x.Code == permission.Code))
                            item.Selected = true;
                        Permissions.Add(item);
                    }
                }
            }
        }
        public IActionResult OnPost(EditRole command)
        {
            var result = _roleApplication.Edit(command);
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Areas/Admin/Pages/Ceremonies/Create.cshtml
@model Haidarieh.Application.Contracts.Ceremony.CreateCeremony
@{
                <link rel="stylesheet" href="~/AdminTheme/assets/css/jquery.Bootstrap-PersianDateTimePicker.css">
                            <script src="~/AdminTheme/assets/js/jquery.Bootstrap-PersianDateTimePicker.js"></script>
}


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ایجاد مراسم جدید</h4>
</div>

<form asp-page="./Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">

    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Title" class="control-label">مراسم</label>
                    <select type="text" class="form-control" asp-for="CalendarId" asp-items='new SelectList(@Model.Calendars,"Id","Title")'>
                        <option value="0">انتخاب مراسم</option>
                    </select>
                    <span asp-validation-for="CalendarId" class="error"></span>
                </div>
            </div>
            @*<div class="col-md-12">
            <div class="form-group">
                <label asp-for="GuestId" class="control-label">میهمان</label>
                <select type="text" class="form-control" asp-for="GuestId" asp-items='new SelectList(Model.Guests,"Id","FullName")'>
                    <option value="0">انتخاب میهمان</option>
                </select>
                <span asp-validation-for="GuestId" class="error"></span>
            </div>
        </div>*@

            @*<div class="col-md-12">
            <div class="form-group">
                <label asp-for="Title" class="control-label">عنوان مراسم</label>
                <input type="text" class="form-control" asp-for="Title">
                <span asp-validation-for="Title" class="error"></span>
            </div>
        </div>*@
            @*<div class="col-md-6">
            <div class="form-group">
                <label asp-for="CeremonyDate" class="control-label">تاریخ برگزاری</label>
                <input type="text" class="form-control persianDateTimeInput" asp-for="CeremonyDate">
                <span asp-validation-for="CeremonyDate" class="error"></span>
            </div>
        </div>*@

            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="CeremonyDate" class="control-label">تاریخ برگزاری</label>
                    <div class="input-group">
                        <input type="text" class="form-control" asp-for="CeremonyDate" data-mddatetimepicker="true" data-trigger="click" data-targetselector="#CeremonyDate" data-enabletimepicker="true" data-isgregorian="false" data-englishnumber="false">
                        <span class="input-group-addon datepicker"><i class="glyphicon glyphicon-calendar"></i></span>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="IsLive" class="control-label">وضعیت پخش زنده </label><br />
                    <input type="radio" class="radio-inline" name="IsLive" asp-for="IsLive" value="1" checked="checked">دارد
                    <input type="radio" class="radio-inline" name="IsLive" asp-for="IsLive" value="0">ندارد
                    <span asp-validation-for="IsLive" class="error"></span>
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="BannerFile" class="control-label">فایل بنر</label>
                    <input type="file" class="form-control" asp-for="BannerFile" accept="image/*">
                    <span asp-validation-for="BannerFile" class="error"></span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Image" class="control-label">عکس</label>
                    <input type="file" class="form-control" asp-for="Image" accept="image/*">
                    <span asp-validation-for="Image" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="ImageTitle" class="control-label">عنوان عکس</label>
                    <input type="text" class="form-control" asp-for="ImageTitle" onchange="fillField('ImageTitle', 'ImageAlt')">
                    <span asp-validation-for="ImageTitle" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="ImageAlt" class="control-label">توضیح عکس در گوگل</label>
                    <input type="text" class="form-control" asp-for="ImageAlt">
                    <span asp-validation-for="ImageAlt" class="error"></span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Keywords" class="control-label">کلمات کلیدی</label>
                    <input type="text" class="form-control" asp-for="Keywords" onchange="makeSlug('Keywords', 'Slug')">
                    <span asp-validation-for="Keywords" class="error"></span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Slug" class="control-label">اسلاگ</label>
                    <input type="text" class="form-control" asp-for="Slug">
                    <span asp-validation-for="Slug" class="error"></span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="MetaDescription" class="control-label">شرح</label>
                    <textarea class="form-control autogrow" asp-for="MetaDescription"
                              style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
                    <span asp-validation-for="MetaDescription" class="error"></span>
                </div>
            </div>

        </div>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>


<script>
    $('.persianDateInput').persianDatepicker({
        format: 'YYYY/MM/DD hh:mm:ss',
        autoClose: true,
        initialValueType: "persian",

        initialValue: true
    });
</script>
<script src="~/AdminTheme/assets/js/jalaali.js"></script>

ServiceHost/Areas/Admin/Pages/Ceremonies/Edit.cshtml
@model Haidarieh.Application.Contracts.Ceremony.EditCeremony
@{
    <script src="~/AdminTheme/assets/js/jalaali.js"></script>
    <link rel="stylesheet" href="~/AdminTheme/assets/css/jquery.Bootstrap-PersianDateTimePicker.css"> 
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش مراسم @Model.Title</h4>
</div>

<form asp-page="./Index" asp-page-handler="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Title" class="control-label">عنوان مراسم</label>
                    <input type="text" class="form-control" asp-for="Title">
                    <span asp-validation-for="Title" class="error"></span>
                </div>
            </div>
            @*<div class="col-md-6">
                <div class="form-group">
                    <label asp-for="CeremonyDate" class="control-label">تاریخ برگزاری</label>
                    <input type="text" class="form-control persianDateInput" asp-for="CeremonyDate">
                    <span asp-validation-for="CeremonyDate" class="error"></span>
                </div>
                </div>*@
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="CeremonyDate" class="control-label">تاریخ برگزاری</label>
                    <div class="input-group">
                        <input type="text" class="form-control" asp-for="CeremonyDate" asp-format="{0:yyyy-MM-ddTHH:mm}" data-mddatetimepicker="true" data-trigger="click" data-targetselector="#CeremonyDate" data-enabletimepicker="true" data-isgregorian="false" data-englishnumber="false">
                        <span class="input-group-addon datepicker"><i class="glyphicon glyphicon-calendar"></i></span>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="IsLive" class="control-label">وضعیت پخش زنده </label><br />
                    <input type="radio" class="radio-inline" name="IsLive" asp-for="IsLive" value="True">دارد
                    <input type="radio" class="radio-inline" name="IsLive" asp-for="IsLive" value="False">ندارد
                    <span asp-validation-for="IsLive" class="error"></span>
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="BannerFile" class="control-label">فایل بنر</label>
                    <input type="file" class="form-control" asp-for="BannerFile" accept="image/*">
                    <span asp-validation-for="BannerFile" class="error"></span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Image" class="control-label">عکس</label>
                    <input type="file" class="form-control" asp-for="Image" accept="image/*">
                    <span asp-validation-for="Image" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="ImageTitle" class="control-label">عنوان عکس</label>
                    <input type="text" class="form-control" asp-for="ImageTitle" onchange="fillField('ImageTitle', 'ImageAlt')">
                    <span asp-validation-for="ImageTitle" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="ImageAlt" class="control-label">توضیح عکس در گوگل</label>
                    <input type="text" class="form-control" asp-for="ImageAlt">
                    <span asp-validation-for="ImageAlt" class="error"></span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Keywords" class="control-label">کلمات کلیدی</label>
                    <input type="text" class="form-control" asp-for="Keywords" onchange="makeSlug('Keywords', 'Slug')">
                    <span asp-validation-for="Keywords" class="error"></span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Slug" class="control-label">اسلاگ</label>
                    <input type="text" class="form-control" asp-for="Slug">
                    <span asp-validation-for="Slug" class="error"></span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="MetaDescription" class="control-label">شرح</label>
                    <textarea class="form-control autogrow" asp-for="MetaDescription"
                              style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
                    <span asp-validation-for="MetaDescription" class="error"></span>
                </div>
            </div>
        </div>
        <input type="hidden" asp-for="Id" value="@Model.Id">
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

<script src="~/AdminTheme/assets/js/jquery.Bootstrap-PersianDateTimePicker.js"></script>


@*<script>
        $('.persianDateInput').persianDatepicker({
            format: 'YYYY/MM/DD',
            autoClose: true,
            initialValue:true,
            initialValueType: "persian"
        });
    </script>*@

ServiceHost/Areas/Admin/Pages/Ceremonies/Index.cshtml
@page
@model ServiceHost.Areas.Admin.Pages.Ceremonies.IndexModel

@{ Layout = "Shared/_AdminLayout";
    ViewData["title"] = " مراسمات"; }

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
        <p class="pull-left">
            <a class="btn btn-success btn-lg" href="#showmodal=@Url.Page("./Index", "Create")">ایجاد مراسم جدید</a>
            @*<a class="btn btn-warning btn-lg" href="#showmodal=@Url.Page("./Index", "Log")">مشاهده سوابق مراسم</a>*@
        </p>
    </div>
</div>

@*<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در مراسمات</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Title"></label>
                        <input class="form-control" asp-for="SearchModel.Title" placeholder="نام مراسم">
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>*@

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست مراسمات</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>عکس</th>
                                    <th>تاریخ برگزاری</th>
                                    <th>مراسم عنوان</th>
                                    @*<th>میهمان</th>*@
                                    <th>وضعیت پخش زنده</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Ceremonies)
                                {
                    <tr>
                        <td>@item.Id</td>
                        <td>
                            <img src="~/@item.Image" style="width: 100px; height: 100px" />
                        </td>
                        <td>@item.CeremonyDateFA</td>
                        <td>@item.Title</td>
                        @*<td>@item.</td>*@
                        <td class="text-center">
                            @if (item.IsLive)
                            {
            <i class="fa fa-check fa-2x text-success"></i> }
        else
        {
<i class="fa fa-remove fa-2x text-danger"></i>}

                        </td>
                        <td>
                            <a class="btn btn-warning pull-right m-rl-5"
                               href="#showmodal=@Url.Page("./Index","Edit", new { id = item.Id })">
                                <i class="fa fa-edit"></i> ویرایش
                            </a>
                        </td>
                    </tr>
}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}

ServiceHost/Areas/Admin/Pages/Ceremonies/OperationLog.cshtml
@model List<Haidarieh.Application.Contracts.Ceremony.CeremonyOperationViewModel>
@{
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">سوابق مراسم</h4>
</div>

<div class="modal-body">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th>عنوان</th>
                <th>عملیات</th>
                <th>عملگر</th>
                <th>تاریخ</th>
                <th>توضیحات</th>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="text-white @(item.Operation==1 ? "bg-success" : "bg-danger")">
                    <td>@item.Id</td>
                    <td>@item.Ceremony</td>
                    <td>
                        @if (item.Operation == 1)
                        {
                            <span>ایجاد</span>
                        }
                        else if (item.Operation == 2)
                        {
                            <span>ویرایش</span>
                        }
                    </td>
                    <td>@item.OperatorName</td>
                    <td>@item.OperationDate</td>
                    <td>@item.Description</td>
                </tr>
            }

        </tbody>
    </table>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
</div>